

spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.10.65:3306/sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      #defaultZone:  http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/ #注册中心的地址
      defaultZone:  http://localhost:8761/eureka/ #注册中心的地址
server:
  port: 8081


